### ISSUE TITLE
'enter' does not always select the correct match

### ISSUE THREAD

**Issue by siegebell** [siegebell/vsc-incremental-search#1]
_Submitted by Bill S. via email_

Reproduce:
1. Create empty text file
2. Enter three lines:
   
   ```
   
   test1
   test2
   ```
3. Position cursor at top of file and press ctrl+i to start incremental search
4. Type 'test' as search term and press enter - 'test' in 'test1' highlighted as expected
5. Press ctrl+i to incremental search to next match - 'test' in 'test2' highlighted as expected
6. Press enter to end incremental search - 'test' in 'test1' on first line selected - not expected - I expected 'test' in 'test2' on second line to be selected

Both enter and esc in step 6 produce the same behavior (selection moves "backwards", not as expected).

Do I misunderstand how to use the extension? I am using vscode 1.5.1.

Thanks!

**Comment by Bill-Stewart** [comment]
Thanks for taking a look at it.

**Comment by siegebell** [comment]
This is caused by [vscode #11503](https://github.com/Microsoft/vscode/issues/11503).

**Comment by siegebell** [comment]
...and will be fixed in vscode 1.6.0, to be released at the end of this week.
